apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
  namespace: micro-service-101
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend   # Make sure this matches your SecretStore name
    kind: SecretStore
  target:
    name: my-app-secret   # Name of the K8s Secret that will be created
    creationPolicy: Owner
  data:
    - secretKey: app      # Name of the key inside the Kubernetes Secret
      remoteRef:
        key: kv/data/my-app  # Full path of the Vault secret
        property: data.app
