name: TFLint Check

on:
  push:
    branches:
      - main
  #pull_request:

jobs:
  tflint:
    name: Run TFLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Initialize TFLint
        run: tflint --init
 
      - name: Run TFLint on All Modules
        run: tflint --chdir=modules/ --recursive
        continue-on-error: true
